### ISSUE TITLE
error to installation 

### ISSUE THREAD

**Issue by tylerhindi1** [Mixeway/MixewayHub#38]
i get errors when i am installing

![image](https://user-images.githubusercontent.com/85779786/185780072-731a3d41-0b11-4558-9f77-4956250f40ee.png)

**Comment by siewer** [comment]
Lot of problems here probably.

to start what is Your docker/docker-compose version? Just checked and tried to run it with:
```
gs:mixeway gs$ docker-compose version
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
```
and I can confirm that it works.

Valid output log should look something like this:
```
gs:mixeway gs$ docker-compose up
Starting MixerDB ... done
Creating MixerBackend ... done
Creating MixewayFrontend ... done
Attaching to MixerDB, MixerBackend, MixewayFrontend
MixerDB            |
MixerDB            | PostgreSQL Database directory appears to contain a database; Skipping initialization
MixerDB            |
MixerDB            | 2022-08-21 08:26:13.923 UTC [1] LOG:  starting PostgreSQL 14.5 (Debian 14.5-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
MixerDB            | 2022-08-21 08:26:13.923 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
MixerDB            | 2022-08-21 08:26:13.923 UTC [1] LOG:  listening on IPv6 address "::", port 5432
MixerDB            | 2022-08-21 08:26:13.928 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
MixerDB            | 2022-08-21 08:26:13.935 UTC [26] LOG:  database system was shut down at 2022-08-21 08:19:41 UTC
MixerDB            | 2022-08-21 08:26:13.944 UTC [1] LOG:  database system is ready to accept connections
MixewayFrontend    | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
MixewayFrontend    | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
MixewayFrontend    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
MixewayFrontend    | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
MixewayFrontend    | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
MixewayFrontend    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
MixewayFrontend    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
MixewayFrontend    | /docker-entrypoint.sh: Configuration complete; ready for start up
```


Have You made any changes to the `docker-compose.yaml` file?

**Comment by tylerhindi1** [comment]
`
┌──(root㉿kali)-[~/tools/mixeway]
└─#  docker-compose version
Docker Compose version v2.1.1

`

i changed only port number

**Comment by siewer** [comment]
can You paste Your dockerfile? I would like to reproduce the problem and propose a solution

**Comment by tylerhindi1** [comment]
version: '3.0'
services:
  MixerDB:
    container_name: MixerDB
    image: postgres:latest
    command: postgres -c 'max_connections=200'
    environment:
      - POSTGRES_DB=mixer
      - POSTGRES_USER=mixeruser
      - POSTGRES_PASSWORD=mixerpassword
    ports:
      - 5431:5431
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
  MixerBackend:
    container_name: MixerBackend
    image: mixeway/backend:latest
    env_file:
      - environments
    ports:
      - 8441:8441
    volumes:
      - ./pki/:/etc/pki
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - MixerDB
  MixewayFrontend:
    container_name: MixewayFrontend
    image: mixeway/frontend:latest
    volumes:
      - ./pki/:/etc/pki
    ports:
      - 441:441
    depends_on:
      - MixerBackend
volumes:
  pgdata:

**Comment by tylerhindi1** [comment]
version: '3.0'
services:
  MixerDB:
    container_name: MixerDB
    image: postgres:latest
    command: postgres -c 'max_connections=200'
    environment:
      - POSTGRES_DB=mixer
      - POSTGRES_USER=mixeruser
      - POSTGRES_PASSWORD=mixerpassword
    ports:
      - 5431:5431
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
  MixerBackend:
    container_name: MixerBackend
    image: mixeway/backend:latest
    env_file:
      - environments
    ports:
      - 8441:8441
    volumes:
      - ./pki/:/etc/pki
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - MixerDB
  MixewayFrontend:
    container_name: MixewayFrontend
    image: mixeway/frontend:latest
    volumes:
      - ./pki/:/etc/pki
    ports:
      - 441:441
    depends_on:
      - MixerBackend
volumes:
  pgdata:

**Comment by siewer** [comment]
For some reason I am unable to reproduce Your error.

However there are few things that are worth to mention:
* Your change in ports is incorrect. `docker-compose` ports syntax is: `{docker.host.port}:{docker.container.port} which means that first one os the port on which the second one will be exposed. You should change only the first one as that change won't affect the container itself. Take `MixewayFrontend` for example. Container is starting the Nginx server on `443` port. If You set port mapping as `441:441` it means that 441 port in container will be exposed at 441 port at host, but at container there is nothing listening on port 441. It should be `441:443`


I have reviewed Your docker file and this one works at my workstation:
```
version: '3.0'
services:
  MixerDB:
    container_name: MixerDB
    image: 'postgres:latest'
    command: postgres -c 'max_connections=200'
    environment:
      - POSTGRES_DB=mixer
      - POSTGRES_USER=mixeruser
      - POSTGRES_PASSWORD=mixerpassword
    ports:
      - '5431:5431'
    volumes:
      - 'pgdata:/var/lib/postgresql/data:rw'
  MixerBackend:
    container_name: MixerBackend
    image: 'mixeway/backend:latest'
    env_file:
      - environments
    ports:
      - '8441:8441'
    volumes:
      - './pki/:/etc/pki'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    depends_on:
      - MixerDB
  MixewayFrontend:
    container_name: MixewayFrontend
    image: 'mixeway/frontend:latest'
    volumes:
      - './pki/:/etc/pki'
    ports:
      - '441:443'
    depends_on:
      - MixerBackend
volumes:
  pgdata:
```

Mixeway is available at `https://localhost:441`
